### ISSUE TITLE
The required version of the fabric launcher doesn't exist

### ISSUE THREAD

**Issue by McSkellyHo** [vini2003/Body-Shuffle#1]
When I launch minecraft, it doesn't start and says that the fabric launcher has to be version 0.30.0 or higher. But when I go to the fabric website, the latest version is 0.7.1.
![Snímek obrazovky (843)](https://user-images.githubusercontent.com/78847349/109706255-03450600-7b99-11eb-90e7-6a24d3447b05.png)
![Snímek obrazovky (844)](https://user-images.githubusercontent.com/78847349/109706259-03dd9c80-7b99-11eb-83be-d5b3f1914189.png)

**Comment by vini2003** [comment]
This is Fabric API's version, not Fabric Loader.

**Comment by McSkellyHo** [comment]
Oh okay, API wasn't written in it so I thought it was the launcher, thanks!
